homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 171.3
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include includes/customize.yaml

zone:
  name: home
  latitude: !secret latitude
  longitude: !secret longitude
  icon: mdi:home
  radius: 500

frontend:
updater:
history:
logbook:
discovery:

http:
 api_password: !secret http_password

sun:

wemo:

zwave:
  usb_path: /dev/ttyACM0

emulated_hue:
  type: alexa
  host_ip: 192.168.1.147
  expose_by_default: false

device_tracker:
  platform: unifi
  username: !secret unifi_username
  password: !secret unifi_password
  track_new_devices: false
  consider_home: 30

alarm_control_panel:
  platform: simplisafe
  username: !secret simplisafe_username
  password: !secret simplisafe_password

media_player:
  platform: webostv
  name: Office TV
  mac: 14:C9:13:2C:F1:E0
  host: 192.168.1.138
  customize:
    sources:
      - livetv
      - plex
      - netflix
      - hdmi1

camera:
  platform: generic
  still_image_url: http://www.spc.noaa.gov/products/outlook/day1otlk_1630.gif
  name: Today's outlook

camera 2:
  platform: generic
  still_image_url: http://www.spc.noaa.gov/products/outlook/day2otlk_1730.gif
  name: Tomorrow's outlook

camera 3:
  platform: generic
  still_image_url: http://192.168.1.151:7777/cgi-bin/snapshot.cgi?1
  username: admin
  password: !secret playroom_camera_password
  name: Playroom

automation: !include includes/automations.yaml
group: !include includes/groups.yaml
scene: !include includes/scenes.yaml
