homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 171.3
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include includes/customize.yaml

zone:
  name: home
  latitude: !secret latitude
  longitude: !secret longitude
  icon: mdi:home
  radius: 300

zone 2:
  name: Kid's school
  latitude: !secret school-latitude
  longitude: !secret school-longitude
  icon: mdi:school
  radius: 300

zone 3:
  name: Maryville
  latitude: !secret kschool-latitude
  longitude: !secret kschool-longitude
  icon: mdi:medical-bag
  radius: 500

frontend:
updater:
history:
logbook:
discovery:
config:
http:
 api_password: !secret http_password
sun:

# 3rd party integrations

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: o.mlOjBV1EWxdMMRhi0StjGIAvEa1xGZjy

ifttt:
  key: !secret ifttt-api

tts:
  platform: google

mqtt:
  broker: m13.cloudmqtt.com
  port: 13194
  username: ha
  password: !secret cloudmqtt_password
  client_id: homeassistant
  keepalive: 60

sensor:
  - platform: darksky
    api_key: !secret darksky_api_key
    latitude: !secret latitude
    longitude: !secret longitude
    monitored_conditions:
      - temperature
      - temperature_max
      - temperature_min
      - humidity
      - precip_probability
      - cloud_cover
      - precip_type
  - platform: template
    sensors:
      garage_door_status:
        friendly_name: 'Garage door'
        value_template: '{{ states.cover.garage_door_opener.state }}'


# hardware

ecobee:
  api_key: !secret ecobee-key

cover:
  - platform: myq
    username: justinglow@gmail.com
    password: !secret myq-password
    type: chamberlain

wemo:

light:
  - platform: hue
    host: 192.168.1.108
  - platform: yeelight
    devices:
      192.168.1.137:
        name: Playroom
        transition: 1000

zwave:
  usb_path: /dev/ttyACM0

emulated_hue:
  type: alexa
  host_ip: 192.168.1.147
  expose_by_default: false

device_tracker:
  platform: owntracks

alarm_control_panel:
  platform: simplisafe
  username: !secret simplisafe_username
  password: !secret simplisafe_password

media_player:
  - platform: apple_tv
    host: 192.168.1.136
    login_id: 00000000-05a4-3ddf-e243-4e630a6c4355




#includes

automation: !include includes/automations.yaml
group: !include includes/groups.yaml
scene: !include includes/scenes.yaml

#scripts -- move this to a file later

script:
  flash_lights:
    alias: Flash Lights
    sequence:
      - service: homeassistant.turn_on
        data:
          entity_id:
            - light.living_ceiling_level_2_0
            - switch.wemo_switch
            - light.the_lamp
            - light.cafe_level_5_0
            - light.island_level_11_0
            - light.kitchen_ceiling_level_7_0
            - light.dining_level_9_0
            - light.hallway1_level_10_0
            - light.hallway2_level_11_0
            - switch.kitchen_under_ca_switch_8_0
            - switch.porch_switch_3_0
            - switch.coach_switch_4_0
      - delay:
          seconds: 1
      - service: homeassistant.turn_off
        data:
          entity_id:
            - light.living_ceiling_level_2_0
            - switch.wemo_switch
            - light.the_lamp
            - light.cafe_level_5_0
            - light.island_level_11_0
            - light.kitchen_ceiling_level_7_0
            - light.dining_level_9_0
            - light.hallway1_level_10_0
            - light.hallway2_level_11_0
            - switch.kitchen_under_ca_switch_8_0
            - switch.porch_switch_3_0
            - switch.coach_switch_4_0
      - service: script.turn_on
        data:
          entity_id: script.light_loop
  light_loop:
    alias: Light flash loop
    sequence:
      - delay:
          seconds: 1
      - service: script.turn_on
        data:
          entity_id: script.flash_lights
  light_loop_kill:
    alias: Kill flashing lights
    sequence:
      service: script.turn_off
      data:
        entity_id: script.light_loop

input_boolean:
  vacation_mode:
    initial: off
