################################################
## inside lights
################################################

  - alias: Lights on in the morning
    initial_state: True
    hide_entity: False
    trigger:
      platform: time
      after: '06:45:00'
    action:
      service: scene.turn_on
      entity_id: scene.morning

  - alias: Lights off in the morning on weekdays
    initial_state: True
    hide_entity: False
    trigger:
      platform: time
      after: '08:45:00'
    condition:
      condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    action:
      service: scene.turn_on
      entity_id: scene.all_off

  - alias: Lights on an hour before sunset
    initial_state: True
    trigger:
      platform: time
      after: '16:30:00'
    action:
      service: scene.turn_on
      entity_id: scene.evening

  - alias: Turn off lights when alarm is armed
    initial_state: True
    hide_entity: False
    trigger:
      platform: state
      entity_id: alarm_control_panel.simplisafe
      state: 'armed_home'
    action:
      service: scene.turn_on
      entity_id: scene.bedtime

  - alias: Flash lights when alarm goes off
    trigger:
      platform: state
      entity_id: alarm_control_panel.simplisafe
      state: 'armed_trigger'
    action:
      service: script.light_loop

  - alias: All lights off at night
    initial_state: True
    hide_entity: False
    trigger:
      platform: time
      after: '23:30:00'
    action:
     service: scene.turn_on
     entity_id: scene.all_off

  - alias: Push notification when Kel gets home
    initial_state: True
    hide_entity: False
    trigger:
      platform: state
      entity_id: device_tracker.kphone_kelley_phone
      state: 'home'
    action:
      service: notify.pushbullet
      data:
        message: 'Kelley is arriving home'

  - alias: Push notification when Kel leaves school
    initial_state: True
    hide_entity: False
    trigger:
      platform: state
      entity_id: device_tracker.kphone_kelley_phone
      to: 'not_home'
      from: 'Maryville'
    action:
      service: notify.pushbullet
      data:
        message: 'Kelley left school'

  - alias: Turn on evening tv scene when apple tv is playing
    initial_state: True
    hide_entity: False
    trigger:
      platform: state
      entity_id: media_player.apple_tv
      to: 'playing'
      from: 'paused'
    condition:
      condition: time
      after: '19:00:00'
    action:
      service: scene.turn_on
      entity_id: scene.evening_tv


##################
# Outside lights #
##################

  - alias: Outside lights off at sunrise
    initial_state: True
    hide_entity: False
    trigger:
      platform: sun
      event: sunrise
    action:
      service: switch.turn_off
      entity_id:
        - switch.porch_switch_3_0
        - switch.coach_switch_4_0

  - alias: Outside lights on at sunset
    initial_state: True
    hide_entity: False
    trigger:
      platform: sun
      event: sunset
      offset: "-00:20:00"
    action:
      service: switch.turn_on
      entity_id:
        - switch.porch_switch_3_0
        - switch.coach_switch_4_0

################################################
## alarm
################################################

  - alias: Turn alarm off in the morning
    initial_state: True
    hide_entity: False
    trigger:
      platform: time
      after: '06:45:00'
    action:
      entity_id: alarm_control_panel.simplisafe
      service: alarm_control_panel.alarm_disarm
