################################################
## inside lights
################################################

  - alias: Lights on in the morning
    initial_state: True
    hide_entity: False
    trigger:
      platform: time
      at: '06:45:00'
    condition:
      condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
    action:
      service: scene.turn_on
      entity_id: scene.morning

  - alias: Lights off in the morning on weekdays
    initial_state: True
    hide_entity: False
    trigger:
      platform: time
      at: '08:45:00'
    condition:
      condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    action:
      service: scene.turn_on
      entity_id: scene.all_off

  - alias: Lights on at 4:30
    initial_state: True
    trigger:
      platform: time
      at: '16:30:00'
    condition:
      condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
    action:
      service: scene.turn_on
      entity_id: scene.evening

  - alias: Turn off lights when alarm is armed
    initial_state: True
    hide_entity: False
    trigger:
      platform: state
      entity_id: alarm_control_panel.simplisafe
      to: 'armed_home'
    action:
      service: scene.turn_on
      entity_id: scene.bedtime

  - alias: Flash lights when alarm goes off
    trigger:
      platform: state
      entity_id: alarm_control_panel.simplisafe
      to: 'armed_trigger'
    action:
      service: script.light_loop

  - alias: All lights off at night
    initial_state: True
    hide_entity: False
    trigger:
      platform: time
      at: '23:30:00'
    condition:
      condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
    action:
     service: scene.turn_on
     entity_id: scene.all_off

  - alias: Push notification when garage door opens
    initial_state: True
    hide_entity: False
    trigger:
      platform: state
      entity_id: cover.garage_door_opener
      to: 'open'
      from: 'closed'
    action:
      service: notify.pushbullet
      data:
        message: 'Garage door opened on {{now().strftime("%-m/%-d at %-I:%M:%S %p")}}'

  - alias: Push notification when Kel leaves school
    initial_state: True
    hide_entity: False
    trigger:
      platform: state
      entity_id: device_tracker.kphone_kelley_phone
      to: 'not_home'
      from: 'Maryville'
    action:
      service: notify.pushbullet
      data:
        message: 'Kelley left school on {{now().strftime("%-m/%-d at %-I:%M:%S %p")}}'

  - alias: Push notification if ATV is down
    initial_state: True
    hide_entity: False
    trigger:
      platform: state
      entity_id: media_player.apple_tv
      to: 'unknown'
    action:
      service: notify.pushbullet
      data:
        message: 'Apple TV connection failed'

  - alias: Turn on evening tv scene when apple tv is playing
    initial_state: True
    hide_entity: False
    trigger:
      platform: state
      entity_id: media_player.apple_tv
      to: 'playing'
      from: 'paused'
    condition:
      condition: time
      after: '19:00:00'
      weekday:
        - sun
        - mon
        - tue
        - wed
        - thu
    action:
      service: scene.turn_on
      entity_id: scene.evening_tv

  - alias: When ATV is playing then paused turn on evening scene
    initial_state: True
    hide_entity: False
    trigger:
      platform: state
      entity_id: media_player.apple_tv
      to: 'paused'
      from: 'playing'
    condition:
      condition: time
      after: '19:00:00'
      weekday:
        - sun
        - mon
        - tue
        - wed
        - thu
    action:
      service: scene.turn_on
      entity_id: scene.evening_tv_paused


##################
# Sun automations #
##################

  - alias: Lights off at sunrise
    initial_state: True
    hide_entity: False
    trigger:
      platform: sun
      event: sunrise
    action:
      - service: switch.turn_off
        entity_id:
          - switch.porch_switch_3_0
          - switch.coach_switch_4_0
      - service: light.turn_off
        entity_id:
          - light.playroom

  - alias: Lights on at sunset, low cloud cover
    initial_state: True
    hide_entity: False
    trigger:
      platform: sun
      event: sunset
      offset: "-00:30:00"
    condition:
      condition: numeric_state
      entity_id: sensor.dark_sky_cloud_coverage
      below: '75'
    action:
      - service: switch.turn_on
        entity_id:
          - switch.porch_switch_3_0
          - switch.coach_switch_4_0
      - service: light.turn_on
        entity_id:
          - light.playroom

  - alias: Lights on at sunset, high cloud cover
    initial_state: True
    hide_entity: False
    trigger:
      platform: sun
      event: sunset
      offset: "-02:30:00"
    condition:
      condition: numeric_state
      entity_id: sensor.dark_sky_cloud_coverage
      above: '75'
    action:
      - service: switch.turn_on
        entity_id:
          - switch.porch_switch_3_0
          - switch.coach_switch_4_0
      - service: light.turn_on
        entity_id:
          - light.playroom


################################################
## security
################################################

  - alias: Turn alarm off in the morning
    initial_state: True
    hide_entity: False
    trigger:
      platform: time
      at: '06:45:00'
    condition:
      condition: state
      entity_id: alarm_control_panel.simplisafe
      state: 'armed_home'
    action:
      entity_id: alarm_control_panel.simplisafe
      service: alarm_control_panel.alarm_disarm

  - alias: Turn on inside lights when motion outside is detected
    initial_state: True
    hide_entity: False
    trigger:
      platform: state
      entity_id: binary_sensor.ecolink_unknown_type0004_id0001_sensor_12_0
      to: 'on'
      from: 'off'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: below_horizon
        - condition: or
          conditions:
            - condition: state
              entity_id: alarm_control_panel.simplisafe
              state: 'armed_home'
            - condition: state
              entity_id: alarm_control_panel.simplisafe
              state: 'armed_away'
    action:
      - service: light.turn_on
        entity_id:
          - light.living_ceiling_level_2_0
          - light.kitchen_ceiling_level_7_0
        data:
          brightness: 255
      - service: notify.pushbullet
        data:
          message: 'Back porch motion detected on {{now().strftime("%-m/%-d at %-I:%M:%S %p")}}'

  - alias: Turn inside lights off after 1 minute of inactivity
    trigger:
      platform: state
      entity_id: binary_sensor.ecolink_unknown_type0004_id0001_sensor_12_0
      to: 'off'
      for:
        minutes: 1
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: below_horizon
        - condition: or
          conditions:
            - condition: state
              entity_id: alarm_control_panel.simplisafe
              state: 'armed_home'
            - condition: state
              entity_id: alarm_control_panel.simplisafe
              state: 'armed_away'
    action:
      - service: light.turn_off
        entity_id:
          - light.living_ceiling_level_2_0
          - light.kitchen_ceiling_level_7_0


################################################
## vacation !!!!!!!!!
################################################

  - alias: Vacation scene 1 trigger
    initial_state: True
    hide_entity: False
    trigger:
      platform: time
      at: '20:13:00'
    condition:
      condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
    action:
      service: scene.turn_on
      entity_id: scene.vacation_1

  - alias: Vacation scene 2 trigger
    initial_state: True
    hide_entity: False
    trigger:
      platform: time
      at: '21:06:00'
    condition:
      condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
    action:
      service: scene.turn_on
      entity_id: scene.vacation_2

  - alias: Vacation scene 3 trigger
    initial_state: True
    hide_entity: False
    trigger:
      platform: time
      at: '22:26:00'
    condition:
      condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
    action:
      service: scene.turn_on
      entity_id: scene.vacation_3

  - alias: Vacation scene 4 trigger
    initial_state: True
    hide_entity: False
    trigger:
      platform: time
      at: '23:26:00'
    condition:
      condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
    action:
      service: scene.turn_on
      entity_id: scene.bedtime

  - alias: Vacation scene 5 trigger
    initial_state: True
    hide_entity: False
    trigger:
      platform: time
      at: '00:14:00'
    condition:
      condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
    action:
      service: scene.turn_on
      entity_id: scene.all_off

  - alias: Vacation all off trigger
    initial_state: True
    hide_entity: False
    trigger:
      platform: sun
      event: sunrise
    condition:
      condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
    action:
      service: scene.turn_on
      entity_id: scene.vacation_all_off
