################################################
## lights
################################################

  - alias: Living room lights on at sunset
    initial_state: True
    hide_entity: False
    trigger:
      platform: sun
      event: sunset
    action:
      service: scene.turn_on
      entity_id: scene.evening

  - alias: Christmas lights on when Kelley comes home
    initial_state: True
    hide_entity: False
    trigger:
      platform: state
      entity_id: device_tracker.kelleys_phone
      state: 'home'
    action:
      service: homeassistant.turn_on
      entity_id: switch.wemo_switch

  - alias: Outside lights off at sunrise
    initial_state: True
    hide_entity: False
    trigger:
      platform: sun
      event: sunrise
    action:
      service: switch.turn_off
      entity_id:
        - switch.porch_switch_3_0
        - switch.coach_switch_4_0

  - alias: Outside lights on at sunset
    initial_state: True
    hide_entity: False
    trigger:
      platform: sun
      event: sunset
      offset: "-00:10:00"
    action:
      service: switch.turn_on
      entity_id:
        - switch.porch_switch_3_0
        - switch.coach_switch_4_0

################################################
## alarm
################################################

  - alias: Turn alarm off in the morning
    initial_state: True
    hide_entity: False
    trigger:
      platform: time
      after: '06:45:00'
    action:
      entity_id: alarm_control_panel.simplisafe
      service: alarm_control_panel.alarm_disarm

  - alias: Turn off lights when alarm is armed
    initial_state: True
    hide_entity: False
    trigger:
      platform: state
      entity_id: alarm_control_panel.simplisafe
      state: 'armed_home'
    action:
      service: homeassistant.turn_off
      entity_id: group.all_lights
