################################################
## inside lights
################################################

  - alias: Lights on in the morning
    initial_state: True
    hide_entity: False
    trigger:
      platform: time
      after: '06:45:00'
    action:
      service: scene.turn_on
      entity_id: scene.morning

  - alias: Lights off in the morning on weekdays
    initial_state: True
    hide_entity: False
    trigger:
      platform: time
      after: '08:45:00'
    condition:
      condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    action:
      service: scene.turn_on
      entity_id: scene.all_off

  - alias: Lights on an hour before sunset
    initial_state: True
    trigger:
      platform: sun
      event: sunset
      offset: "-01:00:00"
    action:
      service: scene.turn_on
      entity_id: scene.evening

  - alias: Turn off lights when alarm is armed
    initial_state: True
    hide_entity: False
    trigger:
      platform: state
      entity_id: alarm_control_panel.simplisafe
      state: 'armed_home'
    action:
      service: scene.turn_on
      entity_id: scene.bedtime

  - alias: Flash lights when alarm goes off
    trigger:
      platform: state
      entity_id: alarm_control_panel.simplisafe
      state: 'armed_trigger'
    action:
      service: script.light_loop

  - alias: All lights off at night
    initial_state: True
    hide_entity: False
    trigger:
      platform: time
      after: '23:30:00'
    action:
     service: scene.turn_on
     entity_id: scene.all_off

##################
# Outside lights #
##################

  - alias: Outside lights off at sunrise
    initial_state: True
    hide_entity: False
    trigger:
      platform: sun
      event: sunrise
    action:
      service: switch.turn_off
      entity_id:
        - switch.porch_switch_3_0
        - switch.coach_switch_4_0

  - alias: Outside lights on at sunset
    initial_state: True
    hide_entity: False
    trigger:
      platform: sun
      event: sunset
      offset: "-00:20:00"
    action:
      service: switch.turn_on
      entity_id:
        - switch.porch_switch_3_0
        - switch.coach_switch_4_0

################################################
## alarm
################################################

  - alias: Turn alarm off in the morning
    initial_state: True
    hide_entity: False
    trigger:
      platform: time
      after: '06:45:00'
    action:
      entity_id: alarm_control_panel.simplisafe
      service: alarm_control_panel.alarm_disarm
